### PR TITLE
GitHub ci

### PR DESCRIPTION
**Pull request by duncanpatterson**

### CODE REVIEW

**Comment by duncanpatterson** [comment]
This commit adds basic kernel compilation tests. This tests against

- all LTS and stable kernels
- linux-next
- master

At present the tests are run on a Monday morning at 0200

**Comment by InterLinked1** [comment]
> At present the tests are run on a Monday morning at 0200

Hi Duncan, just one question, wouldn't it make more sense to:

a) Run the checks daily, rather than weekly? (The Asterisk repos run all the tests on a daily basis).
b) Also run the CI against any PR that is submitted (not just on a schedule)

GitHub CI is free for public projects, so at least I'm not sure what the downside would be to more frequent tests.

**Comment by duncanpatterson** [comment]
Good morning

I agree. This is a work in progress at the moment as I learn how github
actions work. There is more coming including mandatory checks on PRs and
bundling everything into a new release.

The good news is that running these tests on my fork was successful and the
master branch currently builds against all current kernel versions (with
the work that Pushkar has been merging and a few extra bits) .

I'll be working on more over the next few days and any input is welcome.

  Duncan.
*Duncan Patterson*
*Director of Engineering*

**Comment by InterLinked1** [comment]
> Good morning I agree. This is a work in progress at the moment as I learn how github actions work. There is more coming including mandatory checks on PRs and bundling everything into a new release. The good news is that running these tests on my fork was successful and the master branch currently builds against all current kernel versions (with the work that Pushkar has been merging and a few extra bits) . I'll be working on more over the next few days and any input is welcome. 

Thanks Duncan for the reply, and sounds good! Great to see everything is working here and thanks for your work on this, this is looking great so far!

My only other recommendation so far is I noticed that there are a bunch of merge commits in the Git history now (e.g. "Merge branch master into foobar" which makes it look a bit messy. I see the actual commits further down, but this adds some confusion. If you look at the asterisk repo, you don't see this although they might have a more sophisticated merge mechanism; but I think it is essentially just "merge and squash" in the GitHub merge UI, rather than the default option. If we could do that going forward, that would keep the history a bit cleaner as we do rely on that to be able to make sense of what and when things are changing.

**Pull request merged**
