### PR TITLE
Update legacy wctdm modules for modern hardware and kernels

### PR DESCRIPTION
**Pull request by tpearson-ssc**
This fixes compilation on 6.8.0-rc8 as well as operation on modern hardware.

Tested on RCS Talos II with an OpenVox A800E card and FXS module

### CODE REVIEW

**Comment by tpearson-ssc** [comment]
@push143smart Thanks for committing the bulk of this patch, but it looks like my fixes to `wctdm` didn't make their way in.  Did you have an objection to them or do you just want me to pull them back out into a separate pull request?

With the fixes, the Wildcard-based devices are stable and run very well on modern hardware including open ISA systems like ppc64el.

**Comment by push143smart** [comment]
Hi @tpearson-ssc ,

The dahdi modules include the necessary fixes for wctdm as a part of eea4cf5aa706ea1a1822d19b485192d809c7bf31

**Comment by tpearson-ssc** [comment]
> Hi @tpearson-ssc ,
> 
> The dahdi modules include the necessary fixes for wctdm as a part of [eea4cf5](https://github.com/asterisk/dahdi-linux/commit/eea4cf5aa706ea1a1822d19b485192d809c7bf31)

Unfortunately these commits are still missing:
https://github.com/asterisk/dahdi-linux/pull/47/commits/ce47beb9b78c65985ba5ec36a15c7e6e2c418465
https://github.com/asterisk/dahdi-linux/pull/47/commits/44bdb580159352d17c56e8a905334b5c173fd5ce

Could they be merged?

**Comment by InterLinked1** [comment]
> > Hi @tpearson-ssc ,
> > The dahdi modules include the necessary fixes for wctdm as a part of [eea4cf5](https://github.com/asterisk/dahdi-linux/commit/eea4cf5aa706ea1a1822d19b485192d809c7bf31)
> 
> Unfortunately these commits are still missing: [ce47beb](https://github.com/asterisk/dahdi-linux/commit/ce47beb9b78c65985ba5ec36a15c7e6e2c418465) [44bdb58](https://github.com/asterisk/dahdi-linux/commit/44bdb580159352d17c56e8a905334b5c173fd5ce)
> 
> Could they be merged?

@tpearson-ssc It may be that this won't get looked at since the PR is closed, I'd recommend opening a new PR with the leftovers so that hopefully it gets looked at!

**Pull request closed without merging**
