### PR TITLE
drivers: Revert removals of widely used drivers.

### PR DESCRIPTION
**Pull request by InterLinked1**
This reverts the 2018 removals of several digital and analog telephony cards that remain very heavily used in the community.
The TDM400P removal was already reverted in a previous commit.
These drivers have been updated to compile successfully in the current tree, accounting for changes since they were removed as well as current gcc warnings.

### CODE REVIEW

**Comment by duncanpatterson** [comment]
If it is alright with you I would prefer to target just build issues for the next release package. We are overdue a release for a lot of compile issues and if we can minimise changes we can also minimise the chances of other issues. Once that next release is out of the way then we can come back to the other PRs. It should only be a week or so I hope.

**Comment by InterLinked1** [comment]
> If it is alright with you I would prefer to target just build issues for the next release package. We are overdue a release for a lot of compile issues and if we can minimise changes we can also minimise the chances of other issues. Once that next release is out of the way then we can come back to the other PRs. It should only be a week or so I hope.

Thanks Duncan, not an issue - I take it master will still be the right place for this so should be fine to revisit after the next release is out!

**Comment by InterLinked1** [comment]
> > If it is alright with you I would prefer to target just build issues for the next release package. We are overdue a release for a lot of compile issues and if we can minimise changes we can also minimise the chances of other issues. Once that next release is out of the way then we can come back to the other PRs. It should only be a week or so I hope.
> 
> Hi, Duncan, now that 3.3.0 is (officially) out, would we be able to get some of these other PRs merged? Thanks!

@duncanpatterson @push143smart Just want to follow up on this... 3.3.0 is out and there hasn't been much activity in months. Could we get some communication on what the current timeframe for stuff is looking like?

Also the Asterisk project recently set up a new mailing list on groups.io - https://groups.io/g/asterisk-dev

It would be nice if there was an official DAHDI mailing list like groups.io/g/dahdi-dev since right now, there is some stuff discussed loosely on the Asterisk list but since they are different teams, a separate mailing list is needed so that all stakeholders can communicate effectively about the project.

Thanks!

**Review by push143smart — APPROVED** [review]

**Comment by duncanpatterson** [comment]
@InterLinked1 As you can see @push143smart has started merging in some of outstanding pull requests. We;ll do a pass of those and hope to get an rc out in the next week or two.

In terms of mailing list there is not a lot of activity on Dahdi so it may make more sense just to keep everything within github. I'll do a bit of research on it but do you see any downside to using github discussions? Opens things up for discussions outside of issues and its only one place containing all the information.

**Comment by InterLinked1** [comment]
> @InterLinked1 As you can see @push143smart has started merging in some of outstanding pull requests. We;ll do a pass of those and hope to get an rc out in the next week or two.

Thanks @duncanpatterson - exciting!

> In terms of mailing list there is not a lot of activity on Dahdi so it may make more sense just to keep everything within github. I'll do a bit of research on it but do you see any downside to using github discussions? Opens things up for discussions outside of issues and its only one place containing all the information.

The same discussion occured with the asterisk-dev list and it basically came down to all the community developers prefer traditional mailing lists as that's the easiest way for everyone to keep in the loop. GitHub Discussions is better than nothing but it doesn't really serve all the functions of a traditional mailing list, and most of us are involved with lots of things that use mailing lists so email is already the one place for everything. I can just compose a message and send it to the list without logging into GitHub and messing with that.

There hasn't been a lot of activity of late since nothing has been happening, but as things pick up steam again, I expect things will heat up again particularly with new features, and a mailing list would ensure that things are seen by as many of the interested stakeholders as possible - many of them also are not on GitHub for philosophical or other reasons, so a mailing list ensures they aren't excluded and we can get their input.

The Asterisk team shut down the old list and set one up at groups.io/g/asterisk-dev at my recommendation - it is completely free with less than 100 users (which the DAHDI list would certainly be under). So a dahdi-dev companion list might be nice - completely free and maintenance-free, no infrastructure to maintain.

**Pull request merged**
